name: GetTrackers

on:
  schedule:
    - cron: '0 0,1,5,11,14,17,22 * * *'
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'
      - name: cache log
        id: cache-log
        uses: actions/cache@v3
        with:
          path: log
          key: bot-logs
      - name: Run pip install wget
        run: pip install wget
      - name: Run python PyTrackers.py
        run: |
          python PyTrackers.py
        working-directory: ./main
      
      - name: Commit Changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🚀 CI Updated

      - name: GitHub Push
        if: steps.commit.outputs.changes_detected == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: ${{github.ref}}

